### ISSUE TITLE
https://dockerpull.com(被墙) 请更换为 https://dockerpull.org

### ISSUE THREAD

**Issue by FanchangWang** [dongyubin/DockerHub#4]
https://dockerpull.com(被墙) 请更换为 https://dockerpull.org

**Comment by Paper-Dragon** [comment]
确实 @dongyubin 

dockerpull.com
![图片](https://github.com/user-attachments/assets/291d96c3-68fc-42a7-84c6-6daf829b6029)

https://dockerpull.org/
![图片](https://github.com/user-attachments/assets/f9071cbe-b505-4a5e-8d53-20191aaa2761)
