### ISSUE TITLE
能否补充一个containerd的配置文件

### ISSUE THREAD

**Issue by rxzy-krli** [dongyubin/DockerHub#5]
因为写起来也挺麻烦的，如果需要我也可以帮忙提供

**Comment by dongyubin** [comment]
可否提供一个，我这边后期加上

**Comment by dongyubin** [comment]
> 因为写起来也挺麻烦的，如果需要我也可以帮忙提供

可否提供一个，我这边后期加上

**Comment by rxzy-krli** [comment]
sudo tee /etc/containerd/config.toml <<EOF
[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = [
        "https://dockerpull.org",
        "https://docker.1panel.dev",
        "https://docker.foreverlink.love",
        "https://docker.fxxk.dedyn.io",
        "https://docker.xn--6oq72ry9d5zx.cn",
        "https://docker.zhai.cm",
        "https://docker.5z5f.com",
        "https://a.ussh.net",
        "https://docker.cloudlayer.icu",
        "https://hub.littlediary.cn",
        "https://hub.crdz.gq",
        "https://docker.unsee.tech",
        "https://docker.kejilion.pro",
        "https://registry.dockermirror.com",
        "https://hub.rat.dev",
        "https://dhub.kubesre.xyz",
        "https://docker.nastool.de",
        "https://docker.udayun.com",
        "https://docker.rainbond.cc",
        "https://hub.geekery.cn",
        "https://docker.1panelproxy.com",
        "https://atomhub.openatom.cn",
        "https://docker.m.daocloud.io",
        "https://docker.1ms.run",
        "https://docker.linkedbus.com"
      ]
EOF

**Comment by rxzy-krli** [comment]
```
sudo systemctl daemon-reload
sudo systemctl restart containerd
```

**Comment by dongyubin** [comment]
已添加，感谢提供
